name: Install Python 2 on macOS

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: 安装 Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"
      
      - name: 添加 Homebrew 旧版本仓库
        run: |
          brew tap-new $USER/python2
          brew extract --version=2.7.18 python@2 $USER/python2
      
      - name: 安装 Python 2
        run: |
          brew install python@2
          echo "/usr/local/opt/python@2/bin" >> $GITHUB_PATH
      
      - name: 验证 Python 2 安装
        run: |
          python2 --version
          pip2 --version