name: Install Python 3 on macOS with Symlinks

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: 安装 Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # 安装最新的 Python 3 版本
          architecture: 'x64'

      - name: 创建软链接
        run: |
          # 创建 python3 -> python 的软链接
          sudo ln -s $(which python3) /usr/local/bin/python
          
          # 创建 pip3 -> pip 的软链接
          sudo ln -s $(which pip3) /usr/local/bin/pip
          
          # 验证软链接是否创建成功
          echo "软链接创建成功："
          ls -l /usr/local/bin/python
          ls -l /usr/local/bin/pip

      - name: 验证安装和软链接
        run: |
          python --version
          pip --version
          python3 --version
          pip3 --version